Repository GSG-G11/Song-Express, pull requests merged in 2022-03, with the labels that each got.

#1 Create project structure
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  public/css/style.css
  public/errors/404.html
  public/errors/500.html
  public/index.html
  public/js/dom.js
  public/js/script.js
  src/app.js
  src/config.js
  src/controllers/index.js
  src/routes/index.js
  src/server.js
  src/test/app.test.js
Labels: Awaiting Review

#4 Create Error Pages
  public/css/error.css
  public/errors/404.html
  public/errors/500.html
Labels: Awaiting Review, Done

#8 3-creating-main-page
  public/css/style.css
  public/img/Tumblr_l_5548516908907.jpg
  public/index.html
Labels: Done

#14 Handle API in backend
  public/css/style.css
  public/index.html
  src/app.js
  src/options.js
Labels: Done

#11 update dom file
  public/js/dom.js
Labels: Awaiting Review

#15 error handlers
  src/app.js
  src/routes/index.js
Labels: Awaiting Review

#19 Connect frontend with backend
  public/css/style.css
  public/img/spinner.svg
  public/index.html
  public/js/dom.js
  src/app.js
Labels: Awaiting Review

#18 fixed button
  public/css/style.css
  public/index.html
  src/app.js
Labels: Awaiting Review

#20 fix search route
  public/js/dom.js
  src/app.js
Labels: Awaiting Review

#23 Signup form and handle it
  package.json
  public/css/signup.css
  public/js/script.js
  public/js/signupDom.js
  public/signup.html
  src/app.js
Labels: Done

#24 updated REadme file
  README.md
Labels: Awaiting Review

#27 Refactor Code and files
  public/index.html
  src/app.js
  src/controllers/APIController.js
  src/controllers/ErrorController.js
  src/controllers/PageController.js
  src/controllers/index.js
  src/middlewares/middlewares.js
  src/routes/ErrorRouter.js
  src/routes/PageRouter.js
  src/routes/index.js
Labels: Awaiting Review

#29 Renamed the application and updated the readme
  README.md
  public/index.html
  public/signup.html
Labels: Awaiting Review

#30 Login form
  public/css/signup.css
  public/css/style.css
  public/img/Tumblr_l_5548516908907.jpg
  public/index.html
  public/js/signupDom.js
  public/signup.html
Labels: Done
